name=Ada
extensions=.adb,.ads,.ada
line_comment=--
strings="'
case_insensitive=yes
doubled_quotes=yes
escape_strings=no
numbers=yes
keywords=abort,abs,abstract,accept,access,aliased,all,and,array,at,begin,body,case,constant,declare,delay,delta,digits,do,else,elsif,end,entry,exception,exit,for,function,generic,goto,if,in,interface,is,limited,loop,mod,new,not,null,of,or,others,out,overriding,package,pragma,private,procedure,protected,raise,range,record,rem,renames,requeue,return,reverse,select,separate,subtype,synchronized,tagged,task,terminate,then,type,until,use,when,while,with,xor
indent_after=begin,loop,then,is,record,case,declare
outdent_before=end,else,elsif,when,exception
