name=Fortran
extensions=.f,.for,.f77,.f90,.f95,.f03,.f08,.F,.F90
line_comment=!
strings="'
case_insensitive=yes
doubled_quotes=yes
escape_strings=no
numbers=yes
keywords=allocate,allocatable,associate,backspace,block,call,case,character,class,close,common,complex,contains,continue,cycle,data,deallocate,dimension,do,double,else,elseif,elsewhere,end,enddo,endif,endselect,entry,equivalence,exit,external,forall,format,function,goto,if,implicit,import,in,include,inout,integer,interface,intrinsic,logical,module,namelist,none,only,open,operator,optional,out,parameter,pause,pointer,precision,print,private,procedure,program,public,pure,read,real,recursive,result,return,rewind,save,select,sequence,stop,subroutine,target,then,type,use,value,where,while,write
indent_after=then,do,select,module,program,subroutine,function,interface,type
outdent_before=end,endif,enddo,endselect,else,elseif,contains
