name=Go
extensions=.go
line_comment=//
block_comment_start=/*
block_comment_end=*/
strings="'`
numbers=yes
escape_strings=yes
keywords=break,case,chan,const,continue,default,defer,else,fallthrough,for,func,go,goto,if,import,interface,map,package,range,return,select,struct,switch,type,var,true,false,nil
indent_after={
outdent_before=}
outdent_chars=}
