name=Makefile
extensions=.mk
filenames=Makefile,makefile,GNUmakefile
line_comment=#
strings="'
numbers=yes
keywords=include,ifdef,ifndef,ifeq,ifneq,else,endif,define,endef,override,export,unexport,private,vpath
