name=Perl
extensions=.pl,.pm
line_comment=#
strings="'
numbers=yes
escape_strings=yes
keywords=my,our,local,sub,use,package,if,elsif,else,unless,while,until,for,foreach,return,last,next,redo,given,when,default
indent_after={
outdent_before=}
outdent_chars=}
