name=Shell
extensions=.sh,.bash,.ksh,.csh
line_comment=#
strings="'
numbers=yes
escape_strings=yes
keywords=case,do,done,elif,else,esac,fi,for,function,if,in,select,then,time,until,while
indent_after=then,do
outdent_before=fi,done,esac,else,elif
